angular.module('carli.entityForms.product',[
    'ui.bootstrap',
    'carli.alerts',
    'common.libraryService',
    'carli.licenseService',
    'common.productService',
    'carli.viewEditDirectives',
    'carli.warnIfUnsaved'
]);
