angular.module('library.subscriptionSelections',[
    'common.collapsible',
    'common.csvExport',
    'common.modalDialog',
    'common.subscriptionHistoryTable',
    'library.licenseList',
    'library.subscriptionProgress',
    'library.subscriptionButton',
    'library.productInfo',
    'library.licenseInfo'
]);
