module.exports = {
    config: require( '../config' ),
    ActivityLog: require('./Entity/ActivityLogRepository'),
    Attachments: require('./Attachments'),
    Auth: require('./Auth'),
    Cycle: require('./Entity/CycleRepository'),
    Library: require('./Entity/LibraryRepository'),
    License: require('./Entity/LicenseRepository'),
    Membership: require('./Entity/MembershipRepository'),
    Notification: require('./Entity/NotificationRepository'),
    NotificationTemplate: require('./Entity/NotificationTemplateRepository'),
    NotificationDraftGenerator: require('./NotificationDraftGenerator'),
    Offering: require('./Entity/OfferingRepository'),
    Product: require('./Entity/ProductRepository'),
    User: require('./Entity/UserRepository'),
    Vendor: require('./Entity/VendorRepository'),
    VendorStatus: require('./Entity/VendorStatusRepository'),
    Store: require('./Store'),
    MemoryStore: require('./Store/MemoryStore'),
    FileStore: require('./Store/FileStore'),
    CouchDbStore: require('./Store/CouchDb/Store'),
    Validator: require('./Validator'),
    VendorCSV: require('./VendorCSV')
};
