angular.module('carli.sections.vendors', [
    'ngSanitize',
    'carli.sections.vendors.edit',
    'carli.vendorService',
    'carli.entityList'
])
    .value('testVendors', [
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus enim est, rhoncus ut ligula a, rhoncus maximus urna. Sed orci augue, cursus eget quam et, dignissim rhoncus enim. Nulla nec gravida dui. Nam at ligula quis nisi condimentum interdum id ac dolor.",adminModule:"Morbi pharetra nisl sed faucibus dictum. Vivamus laoreet orci ex, eget feugiat enim consequat quis. Vestibulum ac ornare nisi. Aliquam eros lacus, sodales vitae iaculis et, finibus eget dui. Mauris et convallis ligula."},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "FOOBAR of New York", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "acme"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"},
        {"type": "Vendor", "name": "ACME Publishing", "contacts": [], "websiteUrl": "http://www.acme.com", "isActive": true, "comments": "foobar"}
    ]);
