source "https://supermarket.chef.io"

cookbook 'build-essential', '~> 2.2.3'
cookbook 'couchdb', '~> 2.5.2'
cookbook 'curl', '~> 2.0.1'
cookbook 'git', '~> 4.3.1'
cookbook 'nginx', '~> 2.7.6'
cookbook 'nodejs', '~> 2.4.0'
cookbook 'ruby', '~> 0.9.3'

metadata
