angular.module('vendor.sections.simultaneousUserPrices',[
    'cgBusy',
    'common.pricingUtils',
    'common.checkbox',
    'common.csvExport',
    'common.libraryService',
    'common.modalDialog',
    'common.productService',
    'vendor.addSuLevelButton',
    'vendor.horizontalScrollSlider',
    'vendor.offeringColorKey',
    'vendor.quickPricing',
    'vendor.vendorCommentsModal'
]);
