angular.module('vendor.sections.simultaneousUserPrices',[
    'cgBusy',
    'common.checkbox',
    'common.libraryService',
    'common.modalDialog',
    'common.productService',
    'vendor.horizontalScrollSlider',
    'vendor.quickPricing'
]);
