version: '3'
services:
  web:
    image: 'docker.pixodev.net:5000/web:1.8.12'
    restart: always
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:80
    networks:
      - select

  db:
    image: 'couchdb:1.6.1'
    restart: always
    networks:
      - select
    volumes:
      - /carli/db/data:/usr/local/var/lib/couchdb
      - /carli/db/etc:/usr/local/var/lib/couchdb

  middleware:
    image: 'docker.pixodev.net:5000/middleware:1.0.0'
    restart: always
    networks:
      - select

networks:
  select: {}
