version: '3'
services:
  web:
    image: docker.pixodev.net:5000/web:1.8.12 #this is the generated image name for now, but will eventually point to the actual repository
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:80
    networks:
      - select

  db:
    image: couchdb:1.6.1
    networks:
      - select
    volumes:
      - /carli/db/data:/opt/couchdb/data
      - /carli/db/etc:/opt/couchdb/etc

  middleware:
   image: docker.pixodev.net:5000/middleware:1.0.0 #this is the generated image name for now, but will eventually point to the actual repository
    networks:
      - select

networks:
  select: {}
