FROM node:8-alpine

# assumes middleware/ contains a copy of CARLI, config, db, middleware, and schemas from the main project
COPY build/middleware /carli/

EXPOSE 3000

WORKDIR /carli
CMD ["node", "middleware/index.js"]