angular.module('carli.mockServices',[
    'carli.mockAlertService',
    'carli.mockCycleService',
    'carli.mockEntityBaseService',
    'carli.mockErrorHandlerService',
    'carli.mockLibraryService',
    'carli.mockLicenseService',
    'carli.mockLocationService',
    'carli.mockOfferingService',
    'carli.mockProductService',
    'carli.mockVendorService'
]);