angular.module('carli.entityForms.license',[
    'common.alerts',
    'common.fileUploadList',
    'carli.cycleService',
    'carli.licenseService',
    'common.productService',
    'carli.selectCycle',
    'common.vendorService',
    'common.viewEditDirectives',
    'carli.entityForms.priceCaps',
]);
