angular.module('carli.entityForms.license',[
    'common.alerts',
    'carli.cycleService',
    'carli.licenseService',
    'common.productService',
    'carli.selectCycle',
    'carli.vendorService',
    'carli.viewEditDirectives'
]);
