angular.module('carli.entityForms.license',[
    'carli.alerts',
    'common.cycleService',
    'carli.licenseService',
    'common.productService',
    'carli.selectCycle',
    'carli.vendorService',
    'carli.viewEditDirectives',
    'carli.warnIfUnsaved'
]);
