angular.module('vendor.sections.siteLicensePrices',[
    'cgBusy',
    'common.carliModules',
    'common.checkbox',
    'common.libraryService',
    'common.productService',
    'vendor.horizontalScrollSlider',
    'vendor.quickPricing',
    'vendor.vendorCommentsModal'
]);
