angular.module('carli.sections.vendors.edit',[
    'carli.alerts',
    'carli.vendorService',
    'carli.viewEditDirectives.viewEditContact',
    'carli.viewEditDirectives.viewEditTextField',
    'carli.viewEditDirectives.viewEditTextArea',
    'carli.viewEditDirectives.viewEditRadios',
    'carli.viewEditDirectives.viewEditCheckbox'
]);
