name 'carli-select'
description 'A basic starter cookbook'
version '1.0.0'
maintainer 'Bryan Cribbs'
maintainer_email 'bryan@pixotech.com'

depends 'build-essential'
depends 'couchdb'
depends 'curl'
depends 'git'
depends 'nginx'
depends 'nodejs'
depends 'ruby'
