angular.module('carli.sections.products.edit',[
    'carli.alerts',
    'carli.productService',
    'carli.viewEditDirectives.viewEditCheckbox',
    'carli.viewEditDirectives.viewEditYesNoOther',
    'carli.viewEditDirectives.viewEditTextField',
    'carli.viewEditDirectives.viewEditTextArea',
    'carli.viewEditDirectives.viewEditRadios'
]);
